INSERT INTO PROJECT ("ID", "NAME", "STARTDATE") VALUES (1, 'ADM','2018-1-3');
INSERT INTO PROJECT ("ID", "NAME", "STARTDATE") VALUES (2, 'CDM','2018-5-5');
INSERT INTO PROJECT ("ID", "NAME", "STARTDATE", "ENDDATE") VALUES (3, 'KLM','2018-5-5','2018-9-8');
INSERT INTO PROJECT ("ID", "NAME", "STARTDATE", "ENDDATE") VALUES (4, 'CDHGM','2018-5-5','2018-8-10');


INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS",PROJECTID) VALUES (1, 'Penny','mcKey','1982-04-10','ACTIVE',1);
INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS",PROJECTID) VALUES (2,'Sheldon','mcKey','1983-10-04','ACTIVE',2);
INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS",PROJECTID) VALUES (3,'Amy','mcKey','1985-10-04','ACTIVE',1);
INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS",PROJECTID) VALUES (4,'Leonard','mcKey','1979-10-04','ACTIVE',2);
INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS") VALUES (5,'Bernadette','mcKey','1970-10-04','INACTIVE');
INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS") VALUES (6,'Raj','mcKey','1980-10-04','INACTIVE');
INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS") VALUES (7,'Howard','mcKey','19090-10-04','DELETED');
INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS") VALUES (8,'Priya','mcKey','1991-10-04','DELETED');