INSERT INTO USER ("ID", "FIRSTNAME", "SURNAME", "DATEOFBIRTH","STATUS") VALUES (1, 'Penny','mcKey','1982-04-10','ACTIVE')
-- INSERT INTO USER ("firstName", "surName", "dateofBirth","status") VALUES ('Sheldon','mcKey','10-04-1982','ACTIVE')
-- INSERT INTO USER ("firstName", "surName", "dateofBirth","status") VALUES ('Amy','mcKey','10-04-1982','ACTIVE')
-- INSERT INTO USER ("firstName", "surName", "dateofBirth","status") VALUES ('Leonard','mcKey','10-04-1982','ACTIVE')
-- INSERT INTO USER ("firstName", "surName", "dateofBirth","status") VALUES ('Bernadette','mcKey','10-04-1982','ACTIVE')
-- INSERT INTO USER ("firstName", "surName", "dateofBirth","status") VALUES ('Raj','mcKey','10-04-1982','ACTIVE')
-- INSERT INTO USER ("firstName", "surName", "dateofBirth","status") VALUES ('Howard','mcKey','10-04-1982','ACTIVE')
-- INSERT INTO USER ("firstName", "surName", "dateofBirth","status") VALUES ('Priya','mcKey','10-04-1982','ACTIVE')